name: 'Daily Job(freetv)'

on:
  schedule:
    - cron: '45 23 * * *'  # 每天UTC时间23:45运行
  workflow_dispatch:
    inputs:
      environment:
        description: 'Daily Job(freetv)'
        required: true
        default: 'production'

jobs:
  run_job:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有写入权限

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main  # 明确拉取main分支

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
    - name: Run Python script (首次生成文件)
      run: python assets/freetv/freetv.py

    - name: Upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: freetv-generated-files
        path: |
          assets/freetv/freetv_output.txt
          assets/freetv/freetv_output_cctv.txt
          assets/freetv/freetv_output_ws.txt
          assets/freetv/freetv_output_other.txt
          
    - name: Commit and push changes
      run: |
        # 配置Git用户信息
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
        # 强制重置工作区，放弃未提交修改
        git reset --hard HEAD
        
        # 拉取远程最新代码
        git pull origin main --rebase
        
        # 重新生成文件
        python assets/freetv/freetv.py
        
        # 确保history/freetv目录存在
        mkdir -p history/freetv
        
        # 核心：清理3天前的旧归档文件
        find history/freetv -name "*.zip" -type f -mtime +3 -delete
        
        # 提交主文件修改
        git add assets/freetv/freetv_output.txt assets/freetv/freetv_output_cctv.txt assets/freetv/freetv_output_ws.txt assets/freetv/freetv_output_other.txt
        git commit -m ":tv:  (Freetv)AutoUpdate $(date +'%Y%m%d')" || echo "No main file changes to commit"
        
        # 生成并提交新的zip归档文件
        current_datetime=$(date +"%Y%m%d_%H%M%S")
        zip_filename="history/freetv/${current_datetime}_freetv_output.zip"
        zip -j "${zip_filename}" assets/freetv/freetv_output.txt
        git add "${zip_filename}"
        git commit -m "(freetv) Archive zipfile: ${current_datetime}" || echo "No zip file changes to commit"
        
        # 推送修改到远程main分支
        git push origin main
        
    - name: Push changes (fallback)
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # 明确指定推送分支
